### ISSUE TITLE
Card Type

### ISSUE THREAD

**Issue by joeljoy** [braintree/android-card-form#4]
Is there any method to get the card type. I mean like mCardForm.getCardType.

**Comment by grantbdev** [comment]
I'm not aware of a method to get the card type, but your activity can implement CardEditText.OnCardTypeChangedListener.

I set the listener with the CardEditText object: `mCardNumber.setOnCardTypeChangedListener(this);` and then you can override `public void onCardTypeChanged(CardType cardType)` which will be called every time the card type changes in the form. I use cardType.name() to get the name of the CardType, which are listed here: https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/java/com/braintreepayments/cardform/utils/CardType.java

**Comment by lkorth** [comment]
@joeljoy: there is not currently any method to access the card type from the form, nor is the card number edit test accessible from the form. Like @grantbdev recommends, if you want to get the card type every time it changes, your best bet is to implement the callback. If you only want to get the card type once a user has submitted the form and you have the card number, you can also just use [`CardType#forCardNumber`](https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/java/com/braintreepayments/cardform/utils/CardType.java#L157).

@grantbdev: I would be careful about setting `CardEditText#setOnCardTypeChangedListener` if you're using the `CardForm` as a whole since it's going to conflict with the card form's use of the card type to [set the cvv hint](https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/java/com/braintreepayments/cardform/view/CardForm.java#L34). Depending on the order of method calls, it could have unexpected results since one of the callbacks won't be called.

The best solution to this is probably to add a method to the `CardForm` to set a card type change listener.

**Comment by lkorth** [comment]
Closing old issue.

This can be accomplished by using `CardType.forCardNumber(mCardForm.getCardNumber)`.
