### ISSUE TITLE
May I say a suggestion?

### ISSUE THREAD

**Issue by lcsvcn** [braintree/android-card-form#83]
[NOTE] This not a bug or issue. Is a suggestion that I might found useful to share:

I loved you library for android, it is simple and easy to use. What I was wondering is if you guys plan to do something visual like this implementation:
https://github.com/adonixis/android-submit-credit-card-flow

I thing it will be nice and It would be great for a big team as braintree to keep this library updated.

Just a suggestion, but I would be lovely to see.

Like some other repo named: android-card-form-visual or something like that.

I made a small search and don`t find anyone hosting a library like that (In react native I have found, but not native android - kotlin)

Thanks for the attention!

**Comment by scannillo** [comment]
Hi @lcsvcn. We're glad you're enjoying working with the Braintree Android SDKs!

Also, thanks for letting us know about this desired feature. Currently, designing a UI like the example you provided is not on our roadmap for development. I am going to close this issue, because it is unlikely we will offer official support for this type of UI. 

You are welcome to implement this UI on your own using a custom Braintree integration. If we ever did implement this UI, we can re-open this ticket. Thank you!
